#:schema ./trunk.schema.json

[build]
target = "./index.html"

[watch]
ignore = []

[serve]
addresses = ["0.0.0.0"]
port = 1420
open = false
ws_protocol = "ws"

# *nix
[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx @tailwindcss/cli -i styles/main.css -o styles/output.css"]

# Windows
[hooks.windows]
command = "cmd"
command_arguments = ["/c", "npx @tailwindcss/cli -i styles\\main.css -o styles\\output.css"]